version: "3"

networks:
  homelab:
    external: true

services:

  # HTTPS + proxy
  proxy:
    image: jc21/nginx-proxy-manager:2.9.20
    container_name: proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
    networks:
      - homelab
    volumes:
      - $VOL_DATA/proxy/data:/data
      - $VOL_DATA/proxy/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - "nas.homelab:$NAS_IP"
      - "minipc.homelab:$MINIPC_IP"
    restart: unless-stopped


  # Databases
  photoprism.mariadb:
    image: mariadb:10.6
    container_name: photoprism.mariadb
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_PASSWORD=$PHOTOPRISM_PASSWORD
      - MYSQL_DATABASE=photoprism
      - MYSQL_USER=photoprism
    networks:
      - homelab
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - $VOL_DATA/photoprism.mariadb:/var/lib/mysql
    restart: unless-stopped

  nextcloud.mariadb:
    image: mariadb:10.6
    container_name: nextcloud.mariadb
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_PASSWORD=$NEXTCLOUD_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - homelab
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - $VOL_DATA/nextcloud.mariadb:/var/lib/mysql
    restart: unless-stopped

  postgresql:
    image: postgres:10.21
    container_name: postgresql
    hostname: postgresql
    environment:
      PUID: "$PUID"
      PGID: "$PGID"
      POSTGRES_PASSWORD: $PORTFOLIO_PASSWORD
      POSTGRES_USER: funds
    volumes:
      - $VOL_DATA/postgresql:/var/lib/postgresql/data
    networks:
      - homelab
    restart: always

  # Front-ends
  checkmk:
    image: macvaz82/checkmk:with_ssmtp
    container_name: checkmk
    environment:
      CMK_PASSWORD: $LOGIN_PASSWORD
    networks:
      - homelab
    volumes:
      - $VOL_DATA/checkmk/monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssmtp:/etc/ssmtp:ro
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    restart: unless-stopped

  nextcloud:
    image: macvaz82/nextcloud:pdf_preview
    container_name: nextcloud
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_PASSWORD=$NEXTCLOUD_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud.mariadb
    networks:
      - homelab
    links:
      - nextcloud.mariadb
    volumes:
      - $VOL_DATA/nextcloud:/var/www/html
      - /mnt/documents:/mnt/documents
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"                 
      PHOTOPRISM_ADMIN_PASSWORD: "$LOGIN_PASSWORD" 
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "https://photo.thehomelab.site"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000 
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false" 
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism.mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: $PHOTOPRISM_PASSWORD
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_UID: $PUID
      PHOTOPRISM_GID: $PGID
      PHOTOPRISM_UMASK: 0000
    working_dir: "/photoprism"
    networks:
      - homelab
    volumes:
      - "/mnt/family:/photoprism/originals"
      - "/mnt/previews/photoprism/storage:/photoprism/storage" 
    links:
      - photoprism.mariadb
    restart: always


  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Europe/Madrid
      - USER=admin
      - PASS=$LOGIN_PASSWORD
      - HOST_WHITELIST=minipc
    networks:
      - homelab
    volumes:
      - $VOL_DATA/transmission/config:/config
      - $VOL_TEMP/bitTorrent:/downloads
      - $VOL_DATA/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Europe/Madrid
    volumes:
      - $VOL_DATA/heimdall/config:/config
    networks:
      - homelab
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      - TZ='Europe/Madrid'
      - PUID=$PUID
      - PGID=$PGID
      - VIRTUAL_HOST=$PIHOLE_VIRTUAL_HOST
    volumes:
      - $VOL_DATA/pihole/etc-pihole:/etc/pihole
      - $VOL_DATA/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
    networks:
      - homelab
    restart: unless-stopped
   
  portfolio:
    image: macvaz82/portfolio:latest
    container_name: portfolio
    hostname: portfolio
    links:
      - postgresql
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - PROJECT_HOME=/app
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - $VOL_DATA/portfolio/portfolio-manager:/app
    networks:
      - homelab
    command: python /app/manage.py runserver 0.0.0.0:8000
    restart: always
